Repository swsnu/swppfall2022-team1, pull requests merged in 2022-11, with the labels that each got.

#65 Implement SchedulingCloseModal
  udong-frontend/app/ui/components/UdongCheckbox.tsx
  udong-frontend/app/ui/components/UdongModal.tsx
  udong-frontend/app/ui/feature/club/post/scheduling/SchedulingCloseModal.tsx
  udong-frontend/app/ui/icons/IcCheck.png
Labels: ㅇㅍㄹㅂ

#67 :recycle: Update a few modals about CloseModalButton
  udong-frontend/app/ui/feature/club/post/scheduling/SchedulingCloseModal.tsx
  udong-frontend/app/ui/feature/shared/DeleteModal.tsx
Labels: ㅇㅍㄹㅂ

#68 :wrench: Front/fix/title input
  udong-frontend/app/ui/feature/club/post/upsert/PostInputView.tsx
  udong-frontend/app/ui/feature/club/post/upsert/create/PostCreateContainer.tsx
  udong-frontend/app/ui/feature/club/post/upsert/edit/PostEditContainer.tsx
Labels: ㅇㅍㄹㅂ

#51 💬 feat: on delete comment
  udong-frontend/app/ui/feature/club/post/detail/CommentItem.tsx
  udong-frontend/app/ui/feature/club/post/detail/PostDetailCommentsView.tsx
Labels: ㅇㅍㄹㅂ

#64 🟢 Front/feat/fake loading
  udong-frontend/app/ui/feature/club/board/BoardContainer.tsx
  udong-frontend/app/ui/feature/home/feed/FeedContainer.tsx
Labels: ㅇㅍㄹㅂ

#52 🍋 feat: choose post type (create & edit)
  udong-frontend/app/ui/components/UdongRadioButton.tsx
  udong-frontend/app/ui/feature/club/board/BoardContainer.tsx
  udong-frontend/app/ui/feature/club/board/PostCreateModal.tsx
  udong-frontend/app/ui/feature/club/post/detail/PostDetailContainer.tsx
  udong-frontend/app/ui/feature/club/post/upsert/AdditionalFieldItem.tsx
  udong-frontend/app/ui/feature/club/post/upsert/PostAdditionalFieldsView.tsx
  udong-frontend/app/ui/feature/club/post/upsert/create/PostCreateContainer.tsx
  udong-frontend/app/ui/feature/club/post/upsert/edit/PostEditContainer.tsx
  udong-frontend/app/ui/feature/home/HomeContainer.tsx
  udong-frontend/app/ui/feature/shared/DeleteModal.tsx
  udong-frontend/pages/club/[clubId]/post/[postId]/edit.tsx
  udong-frontend/pages/club/[clubId]/post/create.tsx
Labels: ㅇㅍㄹㅂ

#70 :art: Front/feat/button mouse
  udong-frontend/app/ui/components/UdongButton.tsx
  udong-frontend/app/ui/components/UdongChip.tsx
  udong-frontend/app/ui/components/UdongHeader.tsx
  udong-frontend/app/ui/components/UdongImage.tsx
  udong-frontend/app/ui/feature/club/tag/TagItem.tsx
  udong-frontend/app/ui/feature/club/tag/TagUpsertModal.tsx
  udong-frontend/app/ui/feature/header/Header.tsx
  udong-frontend/app/ui/feature/home/mydong/AddClubModal.tsx
  udong-frontend/app/ui/feature/home/mydong/CloseModalButton.tsx
  udong-frontend/app/ui/feature/home/mydong/ClubItem.tsx
  udong-frontend/app/ui/feature/home/mydong/MyDongContainer.tsx
  udong-frontend/app/ui/feature/shared/ClickableTag.tsx
  udong-frontend/app/ui/feature/shared/UserItem.tsx
Labels: ㅇㅍㄹㅂ

#58 🎈 feat: add backend models
  udong-frontend/app/domain/model/AnnouncementPost.ts
  udong-frontend/app/domain/model/Club.ts
  udong-frontend/app/domain/model/Comment.ts
  udong-frontend/app/domain/model/DateSchedulingPost.ts
  udong-frontend/app/domain/model/EnrollmentPost.ts
  udong-frontend/app/domain/model/Event.ts
  udong-frontend/app/domain/model/Post.ts
  udong-frontend/app/domain/model/PostType.ts
  udong-frontend/app/domain/model/SchedulingPost.ts
  udong-frontend/app/domain/model/SchedulingPostType.ts
  udong-frontend/app/domain/model/Tag.ts
  udong-frontend/app/domain/model/User.ts
  udong-frontend/app/domain/model/WeekdaySchedulingPost.ts
Labels: WIP

#73 :clubs: Front/fix/dummydata-club
  udong-frontend/app/ui/feature/home/mydong/ClubItem.tsx
  udong-frontend/app/ui/feature/home/mydong/MyDongContainer.tsx
  udong-frontend/app/ui/icons/IcMaple.png
Labels: ㅇㅍㄹㅂ

#74 :lipstick: Change color of TimeTable
  udong-frontend/app/ui/feature/club/post/detail/PostDetailSchedulingView.tsx
  udong-frontend/app/ui/feature/mypage/AddMyScheduleView.tsx
  udong-frontend/app/ui/theme/ColorPalette.ts
Labels: ㅇㅍㄹㅂ

#76 :lipstick: Change UdongChip props
  udong-frontend/app/ui/components/UdongChip.tsx
  udong-frontend/app/ui/feature/club/post/detail/PostDetailContainer.tsx
  udong-frontend/app/ui/feature/club/post/scheduling/SchedulingCloseContainer.tsx
  udong-frontend/app/ui/feature/club/post/scheduling/SchedulingStatusContainer.tsx
  udong-frontend/app/ui/feature/club/post/scheduling/SchedulingUserListView.tsx
  udong-frontend/app/ui/feature/club/post/upsert/PostAdditionalFieldsView.tsx
  udong-frontend/app/ui/feature/club/tag/TagItem.tsx
  udong-frontend/app/ui/feature/shared/ClickableTag.tsx
  udong-frontend/app/ui/feature/shared/ProfileView.tsx
  udong-frontend/app/ui/feature/shared/UserItem.tsx
  udong-frontend/pages/dummy/index.tsx
Labels: needs review

#77 🥟 feat: post dummy data
  udong-frontend/app/domain/model/Club.ts
  udong-frontend/app/domain/model/Event.ts
  udong-frontend/app/domain/model/Post.ts
  udong-frontend/app/domain/model/PostType.ts
  udong-frontend/app/domain/model/Tag.ts
  udong-frontend/app/domain/model/User.ts
  udong-frontend/app/ui/feature/club/board/BoardContainer.tsx
  udong-frontend/app/ui/feature/club/event/detail/EventDetailContainer.tsx
  udong-frontend/app/ui/feature/club/post/detail/PostDetailContainer.tsx
  udong-frontend/app/ui/feature/home/feed/FeedContainer.tsx
  udong-frontend/app/ui/feature/shared/PostItem.tsx
  udong-frontend/app/utility/postItemFormatter.tsx
Labels: WIP

#82 :sparkles: Hide ScrollToTopButton when scrolled
  udong-frontend/app/ui/feature/shared/ScrollToTopButton.tsx
Labels: needs review

#86 Set icon clickable in UdongSelectableIcon
  udong-frontend/app/ui/components/UdongSelectableIcon.tsx
Labels: needs review

#88 :white_check_mark: Implement mypage.test.tsx
  udong-frontend/pages/__tests__/mypage.test.tsx
  udong-frontend/tests/tsconfig.json
  udong-frontend/tests/unit/index.test.tsx
Labels: needs review

#93 Add test-coverage.yml
  .github/workflows/SonarCloud.yml
  .github/workflows/test-coverage.yml
  sonar-project.properties
Labels: needs review

#95 :toolbox: Back/test/common
  udong-backend/requirements.txt
  udong-backend/udong/common/__init__.py
  udong-backend/udong/common/utils.py
Labels: needs review

#98 :heavy_check_mark: Back/test/user
  udong-backend/udong/Makefile
  udong-backend/udong/user/tests.py
Labels: needs review

#94 Report merged coverage to SonarCloud
  .github/workflows/test-coverage.yml
  sonar-project.properties
Labels: needs review

#99 Kill cache for coverage badge
  README.md
Labels: needs review

#101 :hammer: Back/fix/timemodel2
  udong-backend/udong/dummy.py
  udong-backend/udong/timedata/migrations/0003_alter_time_end_time_alter_time_start_time.py
  udong-backend/udong/timedata/models.py
Labels: needs review

#100 :construction_worker: Update sonar-project.properties
  sonar-project.properties
Labels: WIP

#103 :technologist: Update script "yarn run test"
  udong-frontend/package.json
Labels: needs review

#107 :clubs: Back/test/club
  udong-backend/udong/Makefile
  udong-backend/udong/club/tests.py
  udong-backend/udong/common/utils.py
  udong-backend/udong/user/tests.py
Labels: needs review

#113 :hourglass: Back/fix/timemodel3
  udong-backend/udong/post/migrations/0003_scheduling_confirmed_time_alter_scheduling_end_time_and_more.py
  udong-backend/udong/post/models.py
  udong-backend/udong/timedata/migrations/0004_remove_time_scheduling_alter_time_event.py
  udong-backend/udong/timedata/models.py
Labels: needs review

#114 :hammer_and_wrench: Add id field
  udong-backend/udong/post/serializers.py
Labels: needs review

#117 :white_check_mark: Test Post Detail
  udong-frontend/app/ui/feature/club/post/detail/__tests__/CommentItem.test.tsx
  udong-frontend/app/ui/feature/club/post/detail/__tests__/PostDetailContainer.test.tsx
  udong-frontend/app/ui/feature/club/post/detail/__tests__/PostDetailEnrollmentView.test.tsx
  udong-frontend/app/ui/feature/club/post/detail/__tests__/PostDetailSchedulingView.test.tsx
  udong-frontend/app/ui/feature/mypage/__tests__/AddMyScheduleView.test.tsx
  udong-frontend/app/ui/feature/mypage/__tests__/MyProfileView.test.tsx
Labels: needs review

#119 :man: Fix dummy user
  udong-backend/udong/user/models.py
Labels: needs review

#121 :post_office: Back/test/post
  udong-backend/udong/common/utils.py
  udong-backend/udong/dummy.py
  udong-backend/udong/post/tests.py
Labels: needs review

#125 :white_check_mark: Test scheduling
  udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingCloseContainer.test.tsx
  udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingCloseModal.test.tsx
  udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingHooks.test.ts
  udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingStatusContainer.test.tsx
  udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingStatusTableView.test.tsx
Labels: needs review

#126 :wrench: Exclude pages folder from coverage target
  sonar-project.properties
  udong-frontend/jest.config.js
Labels: needs review

#134 Remove unnecessary else from MyJson compare
  udong-backend/udong/common/utils.py
Labels: needs review

#144 :sparkles: Implement POST, PUT DELETE comment
  udong-backend/udong/comment/serializers.py
  udong-backend/udong/comment/urls.py
  udong-backend/udong/comment/views.py
  udong-backend/udong/post/urls.py
  udong-backend/udong/post/views.py
  udong-backend/udong/udong/urls.py
Labels: needs review

#152 :adhesive_bandage: Do not call serializer.update directly
  udong-backend/udong/comment/views.py
Labels: needs review

#154 :up: Update stubs
  udong-backend/requirements.txt
  udong-backend/udong/club/views.py
  udong-backend/udong/comment/views.py
  udong-backend/udong/post/views.py
  udong-backend/udong/user/views.py
Labels: needs review

#143 :construction_worker: Send purge requeset
  .github/workflows/test-coverage.yml
  README.md
Labels: needs review

#145 🩹 fix: create post tag transformer
  udong-frontend/app/domain/model/Tag.ts
  udong-frontend/app/infra/transformer/BoardPostTransformer.ts
  udong-frontend/app/infra/transformer/PostTagTransformer.ts
Labels: needs review

#148 ✨ feat: get club API
  udong-frontend/app/domain/store/club/ClubSlice.ts
  udong-frontend/app/infra/api/ClubAPI.ts
  udong-frontend/app/ui/feature/club/__test__/ClubContainer.test.tsx
  udong-frontend/app/ui/feature/club/info/ClubProfileView.tsx
  udong-frontend/app/ui/feature/club/info/InfoContainer.tsx
  udong-frontend/app/ui/feature/club/info/__test__/InfoContainer.test.tsx
  udong-frontend/app/ui/feature/shared/PostItem.tsx
  udong-frontend/app/ui/feature/shared/ProfileView.tsx
  udong-frontend/app/utility/handleQueryParams.ts
  udong-frontend/package-lock.json
Labels: needs review

#149 ✨ feat: get club events API
  udong-frontend/app/domain/model/ClubEvent.ts
  udong-frontend/app/domain/model/Event.ts
  udong-frontend/app/domain/model/SchedulingPostType.ts
  udong-frontend/app/domain/model/Time.ts
  udong-frontend/app/domain/store/event/EventSelector.ts
  udong-frontend/app/domain/store/event/EventSlice.ts
  udong-frontend/app/infra/api/ClubAPI.ts
  udong-frontend/app/infra/dto/ClubEventDto.ts
  udong-frontend/app/infra/dto/TimeDto.ts
  udong-frontend/app/infra/transformer/ClubEventTransformer.ts
  udong-frontend/app/infra/transformer/TimeTransformer.ts
  udong-frontend/app/ui/feature/club/ClubContainer.tsx
  udong-frontend/app/ui/feature/club/__test__/ClubContainer.test.tsx
  udong-frontend/app/ui/feature/club/event/EventContainer.tsx
  udong-frontend/app/ui/feature/club/event/__test__/EventContainer.test.tsx
  udong-frontend/app/ui/feature/club/event/list/EventItem.tsx
  udong-frontend/app/ui/feature/club/event/list/EventList.tsx
  udong-frontend/app/ui/feature/club/event/list/EventListView.tsx
  udong-frontend/app/ui/feature/club/event/list/__test__/EventItem.test.tsx
  udong-frontend/app/ui/feature/club/event/list/__test__/EventList.test.tsx
  udong-frontend/app/ui/feature/club/event/list/__test__/EventListView.test.tsx
  udong-frontend/app/utility/__test__/postItemFormatter.test.tsx
  udong-frontend/app/utility/dateTimeFormatter.ts
Labels: needs review

#155 :post_office: Back/feat/get-post2
  udong-backend/udong/post/views.py
Labels: needs review

#156 🍳 Back/feat/enrollment
  udong-backend/udong/post/migrations/0004_participation.py
  udong-backend/udong/post/models.py
  udong-backend/udong/post/serializers.py
  udong-backend/udong/post/urls.py
  udong-backend/udong/post/views.py
Labels: needs review

#169 :memo: Update user schema
  udong-backend/docs/Udong.png
  udong-backend/docs/db-schema.puml
Labels: needs review

#172 :man_artist: Implement logout
  udong-backend/udong/user/views.py
Labels: needs review

#175 Test comment APIs
  udong-backend/udong/comment/tests.py
  udong-backend/udong/post/tests.py
Labels: needs review

#179 Make django admin login work
  udong-backend/udong/dummy.py
  udong-backend/udong/user/migrations/0004_user_is_staff.py
  udong-backend/udong/user/models.py
Labels: needs review

#186 :hammer: Change backend CD domain scheme to https
  .github/workflows/backend-cd.yml
Labels: needs review
